pimcore_admin:
    dataObjects:
        notes_events:
            types:
                - ""
                - "Action manuelle"
                - "Import Adhérent"
                - "Import Pim Socoda"
